# Conjecture

Cerchiamo di capire se non-iso => non zero

Generiamo un caso $d=4$

In [36]:
import numpy as np
from statistics.pmf import PMF
from statistics.OA import OA, genOA, genFiltrations
from statistics.OAIso import allIsomorphisms
from persistence.pers import compute_perm_classes, persistencePairs, WasDistances, BotDistances, L2Distances, AvgDistances, DistancesDistr, wassersteinDistanceDiags
from persistence.distances import wasserstein2DNoDiag, wasserstein1D
from geometry.polytope import Polytope, computePolytope
from geometry.polytope import conditionsOA3, conditionsOA4, conditionsOA5

from scipy.spatial import distance_matrix
import matplotlib.pyplot as plt

In [14]:
oas , _ , _ =genOA(20, d=4)

In [6]:
oas

In [23]:
p1 = oas[0].to_pmf(normalize=True)
print(p1)

[[0.15]
 [0.05]
 [0.  ]
 [0.05]
 [0.  ]
 [0.05]
 [0.1 ]
 [0.1 ]
 [0.  ]
 [0.05]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.1 ]
 [0.05]
 [0.  ]]


In [24]:
p1.compute_moments()

array([[1.  ],
       [0.5 ],
       [0.5 ],
       [0.25],
       [0.5 ],
       [0.25],
       [0.25],
       [0.1 ],
       [0.5 ],
       [0.25],
       [0.25],
       [0.1 ],
       [0.25],
       [0.1 ],
       [0.05],
       [0.  ]])

In [26]:
f1 = p1.compute_filtration()
f1

array([[0.  ],
       [0.5 ],
       [0.5 ],
       [0.75],
       [0.5 ],
       [0.75],
       [0.75],
       [0.9 ],
       [0.5 ],
       [0.75],
       [0.75],
       [0.9 ],
       [0.75],
       [0.9 ],
       [0.95],
       [1.  ]])

In [27]:
persistencePairs(f1 , d=4)

([[2, 3],
  [4, 5],
  [8, 9],
  [6, 7],
  [10, 11],
  [12, 13],
  [14, 15],
  [0, inf],
  [1, inf]],
 [[0.5, 0.75],
  [0.5, 0.75],
  [0.5, 0.75],
  [0.75, 0.9],
  [0.75, 0.9],
  [0.75, 0.9],
  [0.95, 1.0],
  [0.0, inf],
  [0.5, inf]])

In [71]:
p2 = oas[1].to_pmf(normalize=True)
f2 = p2.compute_filtration()
print(p2)

[[0.15]
 [0.  ]
 [0.  ]
 [0.1 ]
 [0.  ]
 [0.1 ]
 [0.1 ]
 [0.05]
 [0.  ]
 [0.1 ]
 [0.1 ]
 [0.05]
 [0.1 ]
 [0.05]
 [0.05]
 [0.05]]


In [39]:
persistencePairs(f2,d=4)

([[2, 3],
  [4, 5],
  [8, 9],
  [6, 7],
  [10, 11],
  [12, 13],
  [14, 15],
  [0, inf],
  [1, inf]],
 [[0.5, 0.75],
  [0.5, 0.75],
  [0.5, 0.75],
  [0.75, 0.9],
  [0.75, 0.9],
  [0.75, 0.9],
  [0.9, 0.95],
  [0.0, inf],
  [0.5, inf]])

In [37]:
wasserstein1D( f1 , f2 )

0.10000000000000005

In [33]:
filtrations = np.column_stack([f1,f2])

In [34]:
WasDistances(filtrations,d=4, noDiag=True)

array([[0.        , 0.07071068],
       [0.07071068, 0.        ]])

In [40]:
p3 = oas[2].to_pmf(normalize=True)
f3 = p3.compute_filtration()
f3

array([[0.  ],
       [0.5 ],
       [0.5 ],
       [0.75],
       [0.5 ],
       [0.75],
       [0.75],
       [0.9 ],
       [0.5 ],
       [0.75],
       [0.75],
       [0.9 ],
       [0.75],
       [0.9 ],
       [0.9 ],
       [1.  ]])

In [41]:
persistencePairs(f3,d=4)

([[2, 3],
  [4, 5],
  [8, 9],
  [6, 7],
  [10, 11],
  [12, 13],
  [14, 15],
  [0, inf],
  [1, inf]],
 [[0.5, 0.75],
  [0.5, 0.75],
  [0.5, 0.75],
  [0.75, 0.9],
  [0.75, 0.9],
  [0.75, 0.9],
  [0.9, 1.0],
  [0.0, inf],
  [0.5, inf]])

In [46]:
permutation = np.array((0,1,3,2))

In [76]:
from statistics.OAIso import applySwapIso, swapIsomorphism
from statistics.OAIso import switchIsomorphism

In [54]:
d = 4
permuted = [swapIsomorphism(k,0,1) for k in range(2**d) ]

In [91]:
permuted = [switchIsomorphism(k,2) for k in range(2**d)]

In [92]:
permuted = np.array(permuted)
permuted

array([ 4,  5,  6,  7,  0,  1,  2,  3, 12, 13, 14, 15,  8,  9, 10, 11])

In [62]:
p1T = PMF(4,p1.values[permuted])
print(p1T)

[[0.15]
 [0.  ]
 [0.05]
 [0.05]
 [0.  ]
 [0.1 ]
 [0.05]
 [0.1 ]
 [0.  ]
 [0.1 ]
 [0.05]
 [0.1 ]
 [0.1 ]
 [0.05]
 [0.1 ]
 [0.  ]]


In [93]:
p1TT = PMF(4,p1TT.values[permuted])
print(p1TT)

[[0.1 ]
 [0.1 ]
 [0.05]
 [0.  ]
 [0.  ]
 [0.05]
 [0.1 ]
 [0.1 ]
 [0.  ]
 [0.05]
 [0.1 ]
 [0.1 ]
 [0.15]
 [0.05]
 [0.  ]
 [0.05]]


In [65]:
f1T = p1T.compute_filtration()
f1T

array([[0.  ],
       [0.5 ],
       [0.5 ],
       [0.75],
       [0.5 ],
       [0.75],
       [0.75],
       [0.9 ],
       [0.5 ],
       [0.75],
       [0.75],
       [0.9 ],
       [0.75],
       [0.95],
       [0.9 ],
       [1.  ]])

In [94]:
f1TT = p1TT.compute_filtration()
f1TT

array([[0.  ],
       [0.5 ],
       [0.5 ],
       [0.75],
       [0.5 ],
       [0.75],
       [0.75],
       [0.85],
       [0.5 ],
       [0.75],
       [0.75],
       [0.85],
       [0.75],
       [0.9 ],
       [0.95],
       [0.95]])

In [69]:
WasDistances( np.column_stack([f1,f1T]), d=4 )

array([[0., 0.],
       [0., 0.]])

In [74]:
wasserstein1D(p1.values,p1T.values)

0.0

In [75]:
print(p1T)

[[0.15]
 [0.  ]
 [0.05]
 [0.05]
 [0.  ]
 [0.1 ]
 [0.05]
 [0.1 ]
 [0.  ]
 [0.1 ]
 [0.05]
 [0.1 ]
 [0.1 ]
 [0.05]
 [0.1 ]
 [0.  ]]
